### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by tomberland** [samuelechu/YoutubePlaylist-Downloader#15]
Hi,

First, your project is really great, I was looking for an application like that.

Secondly, as you can see in the attached image, I can't access to the download or search button in the Youtube Search View. It seems that the following code in SearchWebViewController.swift 
`webView.frame = CGRect(height: view.frame.height - tabBarHeight)` does not work on my iPhone 5S. It's weird because it's working on a iPhone 5S simulator... An intuition?

Thirdly, I please need help. I would like to access the "addPlaylist(name: String)" function (in PlaylistsTableViewController.swift) in another swift class that I created in Main/Misc folder. I want to create a playlist programmatically. I tried to implement something like the "tableDelegate" in DataDownloader.swift but without success. I'm missing something. Can you please give me a trail?

Thank you very much.

Thomas

![youtubeplaylistdownloader](https://cloud.githubusercontent.com/assets/12276865/15015061/ee9e7cde-1209-11e6-97dc-e1c4d6de3ef5.png)

**Comment by samuelechu** [comment]
let tabBarHeight: CGFloat = tabBarController?.tabBar.frame.size.height ?? 0
I think it is setting the tabBarHeight to 0 instead of tabBarController?.tabBar.frame.size.height.
I have an iPhone 5c, so I can give you the tabBarHeight in my case, 49.

So you would want to change that line of code to 
let tabBarHeight: CGFloat = tabBarController?.tabBar.frame.size.height ?? 49

I'll get back to you later on the second question. I'm glad you like my app :)

**Comment by samuelechu** [comment]
There is only one instance of PlaylistsTableViewController. So you can add to AppDelegate.swift: 
var playlistsTable : PlaylistsTableViewController?

Then add similar code from DownloadTableViewController to PlaylistsTableViewController ( the init and setup functions). How it works is that when the app is opened, the instance of both these classes will be accessible through the appDelegate. Then you call functions by accessing these instances.

If you have added everything correctly, you should be able to do this:

let appDel = UIApplication.sharedApplication().delegate as? AppDelegate
let playlistsTable = appDel!.playlistsTable
playlistsTable!.addPlaylist("Sunshine and Waves")
playlistsTable!.refreshPlaylists()

**Comment by tomberland** [comment]
Hello Samuel,

It works, thanks a lot! I'm sorry to bother you, I'm new in the iOS coding,
that's why I'm experiencing some difficulties. It would be very kind of you
if you could answer the following two other questions.

- Is it possible to enable the previous and next buttons when you enlarge
the viewer?
- I would like to create a button (like the "Copy Link" when you press long
on a video) to give you the name of the playlist of the video pressed.
In the "Song Cell" class, I wrote the following code :

let appDel = UIApplication.sharedApplication().delegate as? AppDelegate

context = appDel!.managedObjectContext

let request = NSFetchRequest(entityName: "Song")

request.predicate = NSPredicate(format: "identifier = %@", identifier)

let song = try? context.executeFetchRequest(request)

let playlistName = song![0].valueForKey("playlists") as! NSSet

print("playlistName : ", playlistName)


But it's not working, it's giving me a "Relationship 'playlists' fault" for
the playlistName. Is it possible to retrieve the playlistName like this?
Otherwise, is there another way to give the parameter playlistName to the
"Song Cell" class?

Thank you in advance.
Best regards,

Thomas

2016-05-04 18:24 GMT+02:00 samuelechu <notifications@github.com>:

**Comment by tomberland** [comment]
Hello Samuel,

I finally found a solution to get the playlistName of a song. I created the following method in MiscFuncs.swift : 

```
public class func getPlaylistNameFromFilename(identifier:String) -> String {
        
        let appDel = UIApplication.sharedApplication().delegate as? AppDelegate
        let context = appDel!.managedObjectContext!
        let request = NSFetchRequest(entityName: "Song")
        request.predicate = NSPredicate(format: "identifier = %@", identifier)
        let result : NSArray = try! context.executeFetchRequest(request)
        let resultInNSManagedObject = result[0] as! NSManagedObject
        let relationshipSongPlaylist = resultInNSManagedObject.valueForKey("playlists")
        let playlistNameObject = relationshipSongPlaylist!.valueForKey("playlistName") as! NSSet
        let playlistName = playlistNameObject.allObjects as NSArray
        return playlistName[0] as! String
}
```

It's now possible to get the playlistName of a song everywhere in the project with the following line of code : 
`let playlistName = MiscFuncs.getPlaylistNameFromFilename(identifier)`

I do not know if it's the best solution but it seems to work :)

Regards,
Thomas

**Comment by samuelechu** [comment]
Hello Thomas, 
Sorry for not getting to your last post. I was busy at the time.

I haven't found a way to enable the previous/next buttons when enlarging the player. They are supposed to be 'chapter' buttons. Maybe you may be able to make the next button work if you were able to insert a chapter at the end of each song. 

For getting the playlist name, notice where the Song Cell is created. It's created in Playlist.swift. If you look at the member variables of Playlist, you'll see that there is a variable playlistName that is set when you prepare for the segue to "showPlaylist" (in PlaylistViewController).
----
So you can add the property "playlistName" to SongCell. Change the code in Playlist.swift that initializes       SongCell to include this new property.
Then implement the MenuAction (mimc the code in AppDelegate and MenuAction files)
Finally use SongManager.getPlaylist(playlistName: String) to get the playlist reference.


Let me know if that works. Unfortunately, I can't test it out bc my keyboard doesn't work with vmware :(
And if you have any more questions, don't hesitate to ask. It's cool that you're also dabbling in Swift/iOS!

Best,
Sam
