### ISSUE TITLE
How to delete downloaded video?

### ISSUE THREAD

**Issue by ReDetection** [samuelechu/YoutubePlaylist-Downloader#20]
Because I now have two identical ones (hopefully one of them is 720p)

**Comment by samuelechu** [comment]
Could you help me recreate the issue? How'd it happen

**Comment by ReDetection** [comment]
I just added video to a playlist, then discovered the setting while it was downloading. So I switched quality to 720p, removed entry from the playlist (unfortunately, that did not affected the downloads tab), tried removing whole playlist (no luck also), so I created a new one with the same name, started downloading same video. Now I have two of them in the downloads tab both with checkmarks at the right side

**Comment by samuelechu** [comment]
The downloads tab just displays the videos that you have downloaded. It doesn't necessarily reflect what songs you have in a playlist. Even if there are two of the same videos in your downloads, there should be no duplicates in the playlist. To delete single videos in a playlist, you can swipe left on an entry and a delete button should appear.

I had intended for a video to re-download if the resolution selected was not matching the playlist video's resolution. I'll try updating the code to account for that. Thanks for bringing awareness to this issue!

**Comment by ReDetection** [comment]
Ok. It's still not clear for me how to delete downloaded video to free up some space. Can you please explain?

**Comment by samuelechu** [comment]
There are two ways to delete a downloaded video:
One is to swipe left on the song in the playlist and press the delete button that pops up.
The second is to tap the edit button located on the left top corner of the playlist window, select the songs you want to delete, and press the delete button.

**Comment by ReDetection** [comment]
OK! Clear now, thanks
