### ISSUE TITLE
Black screen on unlock

### ISSUE THREAD

**Issue by ReDetection** [samuelechu/YoutubePlaylist-Downloader#22]
If you accidentally lock the screen while video playback, black screen shown instead of the video when you unlock it. Though audio still work, playback controls are still work, but video is blank.

**Comment by samuelechu** [comment]
I wasn't able to reproduce that behavior. Maybe you only downloaded the audio for that video?

**Comment by ReDetection** [comment]
I did brief check and here is what I got so far:
• issue reproduces on iOS 10 iPhone
• iOS 9 Simulator works OK
• iOS 8 iPod works OK 
I'll try to investigate further

**Comment by samuelechu** [comment]
Okay, I actually haven't updated to iOS 10 yet. I'll download it and let you know if I have the same issue

**Comment by ReDetection** [comment]
I found a workaround without restarting the playback: just switch to another app, and then switch back.

**Comment by samuelechu** [comment]
I finally updated the app to iOS 10 and I was able to reproduce your issue. I will work on fixing the bug soon!
