### ISSUE TITLE
Restrict backing up of downloaded files

### ISSUE THREAD

**Issue by ReDetection** [samuelechu/YoutubePlaylist-Downloader#23]
This might be unintended behaviour that:
1. downloaded videos participate in iTunes Backup
2. downloaded videos may participate in iCloud Backup (fortunately, I had it disabled so it did not caused any problems for me; I'm also not going to enable it, so can't check if it does going to eat much traffic)

This might be a good idea to mark downloads for no backup 😉

**Comment by samuelechu** [comment]
Thanks for the heads up! I'll remember to do that

**Comment by samuelechu** [comment]
Is this still an issue? I'll try fixing it if it is

**Comment by ReDetection** [comment]
I guess it is, I checked backup of march and it contains my videos

**Comment by samuelechu** [comment]
I will implement a fix this weekend!

**Comment by MhmdSalah** [comment]
hello, samuelechu. 
i am interested in making an app to download videos and like this repo, could not contact you so sorry for posting here, can you provide an email?

**Comment by samuelechu** [comment]
Hello, mhmdSalah, my email is samuelechu@gmail.com
