### ISSUE TITLE
Issues with pod install

### ISSUE THREAD

**Issue by Taherismail17** [samuelechu/YoutubePlaylist-Downloader#24]
Doesn't let me pod install:

[!] Unable to satisfy the following requirements:

- `XCDYouTubeKit (~> 2.5.4)` required by `Podfile`
- `XCDYouTubeKit (= 2.5.4)` required by `Podfile.lock`

None of your spec sources contain a spec satisfying the dependencies: `XCDYouTubeKit (~> 2.5.4), XCDYouTubeKit (= 2.5.4)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by samuelechu** [comment]
Try doing a pod update. If that doesn't work, delete the Podfile.lock (and the Pods directory if you have it) and do another pod install.
